version: '2'

services:
  website:
    build: .
    environment:
      PYTHONUNBUFFERED: 'true'
      PORT: 80
      QA_SVCE_HOST: 'localhost'
      QA_SVCE_PORT: 81
      STRIPE_SECRET_KEY: ''
      STRIPE_PUBLISHABLE_KEY: ''
    volumes:
      - '.:/app'
    ports:
      - '80:80'
